Add popup, start with api search and small changes
brunoterragno/hotel-reservation pull request #4
Opened 2022-03-15 11:50 UTC by vivianeLocatelli

- Create the Popup Component,
- Create the Search page,
- Add hotel images to API,
- Small style changes,
- Add react-calendar,
- Add axios.

2022-03-15 12:53 UTC, brunoterragno commented on src/components/Card/index.js
> +  // console.log(mostra());
ainda precisa desse comentário?

2022-03-15 12:58 UTC, brunoterragno commented on src/components/Popup/index.js
> +  const hotelList = data.map((el) => el.rooms);
seria melhor chamar de roomList já que é uma lista de quartos

2022-03-15 13:06 UTC, brunoterragno commented on src/components/Popup/index.js
> +  const hotelList = data.map((el) => el.rooms);
const roomList = data.map((el) => el.rooms)[0];
se adicionar o `[0]` no final não precisa colocar nos outros lugares.

2022-03-15 13:09 UTC, brunoterragno commented on src/components/Popup/index.js
> +    const rate = updateCheckedValue.reduce((sum, currentState, index) => {
Essa função pode ser separada para diminuir a responsabilidade desse método. 

Poderia ser algo como 
const calculateRate = (values, roomlist) => {
  return values.reduce((sum, currentState, index) => {
    if (currentState === true) {
      return sum + roomlist[index].baseRate;
    }
    return sum;
  }, 0);
}

2022-03-15 13:10 UTC, brunoterragno requested changes
Faz a alteração da lógica de cálculo do rate

2022-03-15 15:21 UTC, vivianeLocatelli commented on src/components/Card/index.js
> +  // console.log(mostra());
Não, esqueci de remover.

2022-03-15 15:22 UTC, vivianeLocatelli commented on src/components/Popup/index.js
> +  const hotelList = data.map((el) => el.rooms);
Perfeito, vou alterar.

2022-03-17 12:15 UTC, brunoterragno commented on src/components/Login/index.js
> +            {newUser ? 'Faça Login' : 'Cadastre-se'}
Só vamos ter opção de login por enquanto

2022-03-17 12:23 UTC, merged