Add login with Api and small design changes
brunoterragno/hotel-reservation pull request #5
Opened 2022-03-18 22:06 UTC by vivianeLocatelli

- Add Login with API,
- Add a button on Popup component,
- Add info at the map marker,
- Add private route,
- Design the Profile page.

2022-03-21 12:50 UTC, brunoterragno commented on src/components/Card/index.js
> +        ? [...Array(4)].map((e, i) => {
Poderia colocar essa lógica em um método, algo como showPlaceholder(), assim fica mais limpo.

{isLoading ? showPlaceholder() : data.map().....

2022-03-21 12:53 UTC, brunoterragno commented on src/pages/Profile/index.js
> +  async function getHotelList(data) {
getHotel() 
Não é uma lista

2022-03-21 13:13 UTC, brunoterragno commented on src/pages/Profile/index.js
> +      const response = await api.get('users/bookings', {
essa API na verdade retorna um Array, não um objeto único. Tu fez certinho com o retorno que veio, eu que não formatei direito. Fiz um ajuste, e agora tu precisa buscar as infos de cada hotel na lista.

2022-03-21 13:14 UTC, brunoterragno commented on src/routes/private.js
> +    return <Navigate to='/' />;
muito bom!

2022-03-21 13:14 UTC, vivianeLocatelli commented on src/pages/Profile/index.js
> +  async function getHotelList(data) {
Verdade! Corrigido.

2022-03-21 13:14 UTC, brunoterragno commented on src/routes/index.js
> +          <PrivateRoute
🎉

2022-03-21 13:14 UTC, brunoterragno requested changes
Ajustar o método que recebe o retorno do hotels/bookings para pegar dados de uma lista.

2022-03-22 16:38 UTC, brunoterragno commented on src/pages/Profile/index.js
> +    setUserReservation(userFullInfo);
essa lógica não funciona com uma lista de bookings. Adicionei mais um no retorno da api hotels/bookings, pode testar.

2022-03-23 13:52 UTC, vivianeLocatelli commented on src/pages/Profile/index.js
> +    setUserReservation(userFullInfo);
Certo! Corrigi o problema.

2022-03-23 18:16 UTC, brunoterragno commented on src/pages/Profile/index.js
> +      Promise.all(hotelFullInfo).then(
Muito bom!

2022-03-23 18:16 UTC, brunoterragno approved these changes

2022-03-23 20:09 UTC, merged